-- Snapdoc, version 13 and later: the server stamp is a sequence (it never steps back, unlike the
-- wall clock). Since version 14 the sequence and its trigger are part of supabase-schema.sql,
-- which is safe to run again at any time. Run that file once in the SQL editor of the Snapdoc
-- project; this file is kept only as a pointer.
